name: premake5-ubuntu-codeblocks

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-ubuntu-codeblocks.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_codeblocks'
      - 'projects/**/unsupported_by_premake5_codeblocks'
      - 'submodules/premake-codeblocks'

  pull_request:
    paths:
      - 'projects/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-ubuntu-codeblocks.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_codeblocks'
      - 'projects/**/unsupported_by_premake5_codeblocks'
      - 'submodules/premake-codeblocks'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        runner: ['ubuntu-latest', 'ubuntu-24.04-arm']

    runs-on: ${{matrix.runner}}

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: apt-get update
      run: sudo apt-get update -y

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: add premake codeblocks module
      run: |
        echo "require 'submodules/premake-codeblocks/codeblocks'" >> premake-system.lua

    - name: apt-get install -y codeblocks
      run: sudo apt-get install -y codeblocks

    - name: codeblocks's default configuration
      run: |
        mkdir -p ~/.config/codeblocks
        cp codeblocks/default.conf ~/.config/codeblocks/

    - name: test projects default(gcc)
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as codeblocks requires displays :/
        xvfb-run -a python3 ./test_projects.py premake5 projects codeblocks --scripts=`pwd`

    - name: test projects gcc
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as codeblocks requires displays :/
        xvfb-run -a python3 ./test_projects.py premake5 projects codeblocks --scripts=`pwd` --cc=gcc

    - name: test projects clang
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as codeblocks requires displays :/
        xvfb-run -a python3 ./test_projects.py premake5 projects codeblocks --scripts=`pwd` --cc=clang
