name: premake5-qt-ubuntu-qmake

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt-ubuntu-qmake.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_qmake'
      - 'projects-qt/**/unsupported_by_premake5_qmake'
      - 'submodules/premake-qmake'
      - 'submodules/premake-qt'

  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt-ubuntu-qmake.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_qmake'
      - 'projects-qt/**/unsupported_by_premake5_qmake'
      - 'submodules/premake-qmake'
      - 'submodules/premake-qt'

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        qt-version: ['5.15.0', '6.0.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: add premake qmake module
      run: |
        echo "require 'submodules/premake-qmake/qmake'" >> premake-system.lua

    - name: Installing Qt${{matrix.qt-version}} ubuntu
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{matrix.qt-version}}
        cache: true
        cache-key-prefix: 'qt-action@v4-Qt${{matrix.qt-version}}_ubuntu'

    - name: test qmake
      run: qmake --version

    - name: set path
      run: |
         echo PATH=$PATH:`pwd`
         echo PATH=$PATH:`pwd` >> $GITHUB_ENV
         echo QT_DIR=$QT_ROOT_DIR 
         echo QT_DIR=$QT_ROOT_DIR  >> $GITHUB_ENV

    - name: install libxkbcommon-x11-0 # display dependency
      run: sudo apt-get install libxkbcommon-x11-0

    - name: test projects default(gcc)
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as Qt widget requires displays :/
        xvfb-run -a python3 ./test_projects.py premake5 projects-qt qmake --qt-version=${{ matrix.qt-version }}
