name: premake5-qt5-mac-xcode4

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt5-mac-xcode4.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_xcode4'
      - 'projects-qt/**/unsupported_by_premake5_xcode4'
      - 'submodules/premake-qt'

  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt5-mac-xcode4.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_xcode4'
      - 'projects-qt/**/unsupported_by_premake5_xcode4'
      - 'submodules/premake-qt'

jobs:
  mac:
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: Installing Qt5.15.0 macos
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.0'
        cache: true
        cache-key-prefix: 'qt-action-5.15.0_macos'

    - name: set path
      run: |
         echo PATH=$PATH:`pwd`
         echo PATH=$PATH:`pwd` >> $GITHUB_ENV
         echo QT_DIR=$QT_ROOT_DIR 
         echo QT_DIR=$QT_ROOT_DIR  >> $GITHUB_ENV

    #- name: install libxkbcommon-x11-0 # display dependency
    #  run: sudo apt-get install libxkbcommon-x11-0

    - name: test projects default(clang)
      run: |
        # Cannot use environment variable ($QT_ROOT_DIR ) in command line, so use environment variable (QT_DIR) or its hardcoded value
        python3 ./test_projects.py premake5 projects-qt xcode4 #--qt-root=/home/runner/work/premake-sample-projects/Qt/5.15.0/gcc_64

    - name: test projects gcc
      run: |
        # Cannot use environment variable ($QT_ROOT_DIR ) in command line, so use environment variable (QT_DIR) or its hardcoded value
        python3 ./test_projects.py premake5 projects-qt xcode4 --cc=gcc #--qt-root=/home/runner/work/premake-sample-projects/Qt/5.15.0/gcc_64

    - name: test projects clang
      run: |
        # Cannot use environment variable ($QT_ROOT_DIR ) in command line, so use environment variable (QT_DIR) or its hardcoded value
        python3 ./test_projects.py premake5 projects-qt xcode4 --cc=clang #--qt-root=/home/runner/work/premake-sample-projects/Qt/5.15.0/gcc_64
