name: premake5-qt5-ubuntu-codelite

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - 'codelite/**'
      - '.github/workflows/premake5-qt5-ubuntu-codelite.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_codelite'
      - 'projects-qt/**/unsupported_by_premake5_codelite'
      - 'submodules/premake-codelite'
      - 'submodules/premake-qt'

  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - 'codelite/**'
      - '.github/workflows/premake5-qt5-ubuntu-codelite.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_codelite'
      - 'projects-qt/**/unsupported_by_premake5_codelite'
      - 'submodules/premake-codelite'
      - 'submodules/premake-qt'

jobs:
  linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: apt-get update
      run: sudo apt-get update -y

    - name: sudo apt-get install -y codelite
      run: sudo apt-get install -y codelite

    - name: codelite --version
      run: xvfb-run -a codelite --version || exit 0 # codelite --version returns -1

    - name: Installing Qt5.15.0 ubuntu
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.0'
        cache: true
        cache-key-prefix: 'qt-action-5.15.0_ubuntu'

    - name: set path
      run: |
         echo PATH=$PATH:`pwd`
         echo PATH=$PATH:`pwd` >> $GITHUB_ENV
         echo QT_DIR=$Qt5_Dir
         echo QT_DIR=$Qt5_Dir >> $GITHUB_ENV

    - name: install libxkbcommon-x11-0 # display dependency
      run: sudo apt-get install libxkbcommon-x11-0

    - name: test projects default(clang)
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as Qt widget requires displays :/
        # Cannot use environment variable ($Qt5_Dir) in command line, so use environment variable (QT_DIR) or its hardcoded value
        xvfb-run -a python3 ./test_projects.py premake5 projects-qt codelite #--qt-root=/home/runner/work/premake-sample-projects/Qt/5.15.0/gcc_64

