name: premake5-qt5-windows-msvc-2022

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt5-windows-msvc-2022.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_vs2022'
      - 'projects-qt/**/unsupported_by_premake5_vs2022'
      - 'submodules/premake-qt'

  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt5-windows-msvc-2022.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_vs2022'
      - 'projects-qt/**/unsupported_by_premake5_vs2022'
      - 'submodules/premake-qt'

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Installing Qt - 5.15.0 win64_msvc2019_64 # No 2022 version yet
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.0'
        arch: win64_msvc2019_64
        cache: true
        cache-key-prefix: 'qt-action-5.15.0_win64_msvc2019_64'

    - name: test projects
      run: |
        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects-qt vs2022 --qt-root=$QT_ROOT_DIR 
      shell: bash
