name: premake4-ubuntu-gmake

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/**'
      - '.github/workflows/premake4-ubuntu-gmake.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake5.lua'
      - 'projects/**/unsupported_by_gmake'
      - 'projects/**/unsupported_by_premake4_gmake'

  pull_request:
    paths:
      - 'projects/**'
      - '.github/workflows/premake4-ubuntu-gmake.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake5.lua'
      - 'projects/**/unsupported_by_gmake'
      - 'projects/**/unsupported_by_premake4_gmake'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        runner: ['ubuntu-latest', 'ubuntu-24.04-arm']

    runs-on: ${{matrix.runner}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt-get install premake4
      run: sudo apt-get install -y premake4

    - name: make --version
      run: make --version

    - name: test projects default(gcc)
      run: python3 test_projects.py premake4 projects gmake

    - name: test projects gcc
      run: python3 test_projects.py premake4 projects gmake --cc=gcc

    - name: test projects clang
      run: python3 test_projects.py premake4 projects gmake --cc=clang
