name: premake5-windows-msvc-2019

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/**'
      - 'projects-C#/**'
      - '.github/workflows/premake5-windows-msvc-2019.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_vs2019*'
      - 'projects/**/unsupported_by_premake5_vs2019'

  pull_request:
    paths:
      - 'projects/**'
      - 'projects-C#/**'
      - '.github/workflows/premake5-windows-msvc-2019.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_vs2019*'
      - 'projects/**/unsupported_by_premake5_vs2019'

jobs:
  windows:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          msdev: vs2019
          repository: premake/premake-core

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: test projects (default=msc)
      run: |
        #"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        python3 ./test_projects.py premake5 projects vs2019
      shell: bash

    - name: test projects (clang)
      run: |
        python3 ./test_projects.py premake5 projects vs2019 --cc=clang
      shell: bash

    - name: test projects-C# (default)
      run: python3 ./test_projects.py premake5 projects-C# vs2019
      shell: bash
