name: premake5-ubuntu-gmakelegacy

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/**'
      - '.github/workflows/premake5-ubuntu-gmakelegacy.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_gmakelegacy'
      - 'projects/**/unsupported_by_premake5_gmakelegacy'

  pull_request:
    paths:
      - 'projects/**'
      - '.github/workflows/premake5-ubuntu-gmakelegacy.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_gmakelegacy'
      - 'projects/**/unsupported_by_premake5_gmakelegacy'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        runner: ['ubuntu-latest', 'ubuntu-24.04-arm']

    runs-on: ${{matrix.runner}}

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: make --version
      run: make --version

    - name: test projects default(gcc)
      run: python3 ./test_projects.py premake5 projects gmakelegacy

    - name: test projects gcc
      run: python3 ./test_projects.py premake5 projects gmakelegacy --cc=gcc

    - name: test projects clang
      run: python3 ./test_projects.py premake5 projects gmakelegacy --cc=clang
