name: premake5-qt-windows-msvc-2022

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt-windows-msvc-2022.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_vs2022'
      - 'projects-qt/**/unsupported_by_premake5_vs2022'
      - 'submodules/premake-qt'

  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt-windows-msvc-2022.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_vs2022'
      - 'projects-qt/**/unsupported_by_premake5_vs2022'
      - 'submodules/premake-qt'

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        qt-version: ['6.1.0', '6.7.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Installing Qt - ${{matrix.qt-version}} win64_msvc2019_64 # No 2022 version yet
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{matrix.qt-version}}
        arch: win64_msvc2019_64
        cache: true
        cache-key-prefix: 'qt-action@v4-Qt${{matrix.qt-version}}_win64_msvc2019_64'

    - name: test projects
      run: |
        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects-qt vs2022 --qt-root=$QT_ROOT_DIR --qt-version=${{ matrix.qt-version }}
      shell: bash

    - name: list Qt
      run: |
        ls D:/a/premake-sample-projects/Qt/${{matrix.qt-version}}/msvc2019_64
      shell: bash

    - name: Upload Qt
      uses: actions/upload-artifact@v4
      with:
        name: Qt${{matrix.qt-version}}_win64_msvc2019_lib
        path: |
          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}/msvc2019_64/lib/**

#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}\msvc2019_64\bin\**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}\msvc2019_64\doc\**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}\msvc2019_64\include\**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}/msvc2019_64/lib/**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}/msvc2019_64/mkspec/**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}/msvc2019_64/phrasebooks/**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}/msvc2019_64/plugins/**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}/msvc2019_64/qml/**
#          D:\a\premake-sample-projects\Qt\${{matrix.qt-version}}/msvc2019_64/translation/**
