name: premake5-windows-ninja

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-windows-ninja.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_ninja'
      - 'projects/**/unsupported_by_ninja_windows'
      - 'projects/**/unsupported_by_premake5_ninja'
      - 'submodules/premake-ninja'

  pull_request:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-windows-ninja.yml'
      - '.github/actions/install-premake5/action.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_ninja'
      - 'projects/**/unsupported_by_ninja_windows'
      - 'projects/**/unsupported_by_premake5_ninja'
      - 'submodules/premake-ninja'

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: install ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: ninja --version
      run: ninja --version

    - name: add premake ninja module
      run: |
        echo "require 'submodules/premake-ninja/ninja'" >> premake-system.lua

    - name: Add cl.exe to PATH # microsoft/setup-msbuild doesn't add it :(
      uses: ilammy/msvc-dev-cmd@v1

#    - name: test projects default(msc-v142) # Visual Studio 2019 (version mismatch is not that important, only cl.exe is called)
#      run: |
#        #"C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
#        echo $PATH
#        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects ninja--shell=posix
#      shell: bash

    - name: test projects msc-v143 # Visual Studio 2022
      run: |
        #"C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        echo $PATH
        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects ninja --cc=msc-v143  --shell=posix
      shell: bash

#    - name: test projects gcc
#      run: |
#        echo $PATH
#        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects ninja --cc=gcc  --shell=posix
#      shell: bash
